### ISSUE TITLE
10/4 Update Issue

### ISSUE THREAD

**Issue by Jaeyphf** [hssm/advanced-browser#100]
I'm getting an error when using the add-on after the 10/4 update. I need to disable it to continue using anki. It says this:

```
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-10-03 17:34:38

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Jeff\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\core.py", line 97, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt\browser.py", line 148, in data
  File "C:\Users\Jeff\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\core.py", line 112, in columnData
    return self.browser.customTypes[type].onData(c, n, type)
  File "C:\Users\Jeff\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\advanced_fields.py", line 99, in cFasttimeOnData
    return mw.col.format_timespan(tm)
AttributeError: '_Collection' object has no attribute 'format_timespan'
```

Not sure if it is due to the update or if it is something on my end!

**Comment by yshklarov** [comment]
Me too:

```Debug info:
Anki 2.1.26 (arch-linux-2.1.26-1) Python 3.8.5 Qt 5.15.0 PyQt 5.15.0
Platform: Linux
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2020-10-03 18:59:48
Add-ons possibly involved: ⁨Advanced Browser⁩

Caught exception:
Traceback (most recent call last):
  File "/home/yakov/.anki/addons21/874215009/advancedbrowser/core.py", line 97, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "/usr/lib/python3.8/site-packages/aqt/browser.py", line 148, in data
    return self.columnData(index)
  File "/home/yakov/.anki/addons21/874215009/advancedbrowser/core.py", line 112, in columnData
    return self.browser.customTypes[type].onData(c, n, type)
  File "/home/yakov/.anki/addons21/874215009/advancedbrowser/advanced_fields.py", line 68, in cAvgtimeOnData
    return mw.col.format_timespan(avgtime)
AttributeError: '_Collection' object has no attribute 'format_timespan'
```

Rolling back yesterday's changes here fixes the problem: https://github.com/hssm/advanced-browser/commit/a713d7466cc0a484b7c0f9635feda57faa11f80c

**Comment by hssm** [comment]
I've uploaded a version that reverts this change. Sorry for the trouble, I was fixing a warning from Anki itself but neglected to check which versions it was applicable for (still in dev only).
