### ISSUE TITLE
changing the note id in the table doesn't work (2.1.35)

### ISSUE THREAD

**Issue by ijgnd** [hssm/advanced-browser#106]
I used a new profile without any other add-ons in 21.35 made some notes and then tried to change the nid in the browser table by double clicking it and entering the new value. After saying yes in the confirmation dialog ("Do you really want to change the id of the note ...") I get the following error:

    Caught exception:
    Traceback (most recent call last):
    File "../Anki2/addons21/874215009/advancedbrowser/core.py", line 161, in setData
        r = self.browser.customTypes[type].setData(c, value)
    File "../Anki2/addons21/874215009/advancedbrowser/column.py", line 62, in setData
        return self._setData(*args, **kwargs)
    File "../Anki2/addons21/874215009/advancedbrowser/internal_fields.py", line 49, in setData
        n.flush()
    File "anki/notes.py", line 68, in flush
    File "anki/rsbackend_gen.py", line 344, in update_note
    File "anki/rsbackend.py", line 267, in _run_command
    anki.rsbackend.NotFoundError

I don't know anything about rust so I have no idea what to do about this.

My Advanced Browser settings are:

    {
        "Show internal fields": true,
        "Table content": "Editable",
        "Use a single list for fields": false
    }

About my system: 

    Anki 2.1.35 (84dcaa86) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
    Platform: Linux
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-11-07 11:41:09
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Advanced Browser ['874215009', 2020-10-25T15:10, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    874215009
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    
Thanks for sharing this add-on. 

I think this function is useful.

I know that there's another add-on for changing the nid on ankiweb named [Duplicate and Reorder](https://ankiweb.net/shared/info/1114271285) by swapping nid of neighboring nids. But I liked to be able to directly type in the nid I want.

**Comment by hssm** [comment]
Perhaps the backend no longer allows changing the note IDs from the python bridge. I'm not sure, but this feature may not be possible anymore. I'm not too motivated to debug rust issues. @Arthur-Milchior you may want to investigate whether this is still feasible or not.

**Comment by ijgnd** [comment]
For changing the note id (nid) there are other add-ons like 

- [fast change note-id (dnr fork)](https://ankiweb.net/shared/info/806857685)
- [note organizer FORK (fake/change note creation times)](https://ankiweb.net/shared/info/1287561532)

So it's not worth fixing it in this repo.
