### ISSUE TITLE
Anki 2.1.41beta3 error

### ISSUE THREAD

**Issue by AnKingMed** [hssm/advanced-browser#114]
Damien said he doesnt' expect a lot will be changing so I'm reporting this now. This error happens when clicking to open the browser screen. I know it says its another add-on, but I've tested this over and over and removing Advanced Browser solves the problem

```
Traceback (most recent call last):
  File "aqt/webview.py", line 37, in cmd
  File "aqt/webview.py", line 136, in _onCmd
  File "aqt/webview.py", line 581, in _onBridgeCmd
  File "<decorator-gen-152>", line 2, in _linkHandler
  File "anki/hooks.py", line 89, in decorator_wrapper
  File "anki/hooks.py", line 86, in repl
  File "/Users/Nick/Library/Application Support/Anki2/addons21/zkingofstudytimers/__init__.py", line 616, in myLinkHandler
    return _old(self, url)
  File "aqt/toolbar.py", line 170, in _linkHandler
  File "aqt/toolbar.py", line 188, in _browseLinkHandler
  File "aqt/main.py", line 1069, in onBrowse
  File "aqt/__init__.py", line 101, in open
TypeError: __init__() got an unexpected keyword argument 'card'
```

**Comment by hssm** [comment]
Fixed in new version which I've just uploaded.

**Comment by AnKingMed** [comment]
Working well now! Thanks for the quick fix!
