### ISSUE TITLE
Issues with Anki 2.1.41

### ISSUE THREAD

**Issue by georgez-zgeorge** [hssm/advanced-browser#116]
Hi there. Thanks for your incredible add-on. It appears that it is having some issues in 2.1.41. We receive this error upon opening the browser:
```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.41 (312fa278) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-03-07 08:43:10
Add-ons possibly involved: ⁨Advanced Browser⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/main.py", line 1067, in onBrowse
  File "aqt/__init__.py", line 101, in open
  File "/Users/[user]/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 208, in __init__
    origInit(self, mw, card, search)
  File "<decorator-gen-40>", line 2, in __init__
  File "anki/hooks.py", line 89, in decorator_wrapper
  File "anki/hooks.py", line 81, in repl
TypeError: on_browser_init() takes 3 positional arguments but 5 were given
```
Then this error when closing the Browser:

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.41 (312fa278) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-03-07 08:43:10
Add-ons possibly involved: ⁨Advanced Browser⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/[user]/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 327, in closeEvent
    if not self.saveEvent:
AttributeError: 'AdvancedBrowser' object has no attribute 'saveEvent'
```
Then the browser will not reopen but will give this warning:

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.41 (312fa278) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-03-07 08:43:10
Add-ons possibly involved: ⁨Advanced Browser⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/main.py", line 1067, in onBrowse
  File "aqt/__init__.py", line 101, in open
  File "/Users/[user]/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 208, in __init__
    origInit(self, mw, card, search)
TypeError: newBrowserInit() takes 4 positional arguments but 5 were given
```
Let me know if you have any other questions! Thank you!

**Comment by georgez-zgeorge** [comment]
Oh boy. Now I'm feeling real dumb. I disabled symbols as you type and now it works. Looks like you're good to go!
