### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vega4speed** [hssm/advanced-browser#19]
When I try to add a column from my fields, it get two error message windows. When I close them, they immediately pop back up and prevent me from doing anything else in the application including close it. I have to force end task the application. Thanks in advance for any help.

> An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'

> An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'
Traceback (most recent call last):
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 104, in data
    fld = self.getFld(index)
  File "C:\Users\chip.carden\AppData\Roaming\Anki2\addons\advancedbrowser\core.py", line 86, in getFld
    if id not in self.modelFldObjs:
AttributeError: 'AdvancedDataModel' object has no attribute 'modelFldObjs'

**Comment by hssm** [comment]
You'll have to send me a copy of your collection so I can try to reproduce it.

**Comment by gnprice** [comment]
I hit the same issue after installing the add-on just now, immediately after I went and used the menu to add a field-based column in the browser.

On looking at the code, I think I see the issue -- if you install the add-on in a new Anki install where you haven't previously used the add-on and then try to use it, I think you'll reproduce it as well. It's that in the commit 1295e6deb "Left-align columns maintained by this add-on" which was the new code in 1.5.0, this initialization code:
```
        # Model->flds cache, similar to self.cardObjs
        self.modelFldObjs = {}
```
happens at the end of `__init__`, which is short-circuited by this logic earlier in the function:
```
        if not reloadedCols:
            # We've never used this add-on before. Our initial state will be
            # whatever active columns are already set.
            return
```

I'll attempt a fix.

**Comment by hssm** [comment]
The latest version on AnkiWeb fixes this problem. Thanks @gnprice.
