### ISSUE TITLE
Many errors

### ISSUE THREAD

**Issue by honis56** [hssm/advanced-browser#60]
Hi,

Linux Mint 19.3 Cinnamon

after installing adcanced-browser in
Anki Version 2.1.0beta36 Qt 5.9.5 PyQt 5.10.1
I got this:

Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 57, in loadAddons
    __import__(dir)
  File "/home/br/.local/share/Anki2/addons21/874215009/__init__.py", line 6, in <module>
    from . import advancedbrowser
  File "/home/br/.local/share/Anki2/addons21/874215009/advancedbrowser/__init__.py", line 1, in <module>
    from .core import AdvancedBrowser
  File "/home/br/.local/share/Anki2/addons21/874215009/advancedbrowser/core.py", line 14, in <module>
    from . import config
  File "/home/br/.local/share/Anki2/addons21/874215009/advancedbrowser/config.py", line 36, in <module>
    mw.addonManager.setConfigUpdatedAction(__name__,update)
AttributeError: 'AddonManager' object has no attribute 'setConfigUpdatedAction'

sincerely

**Comment by hssm** [comment]
The version of Anki is too old, and the add-on relies on new features only available in newer versions. You should update to the latest release.

I uploaded a [legacy build](https://github.com/hssm/advanced-browser/releases/tag/Legacy) of the add-on if you would like to try using that instead.
