### ISSUE TITLE
many errors

### ISSUE THREAD

**Issue by honis56** [hssm/advanced-browser#61]
Linux Mint:

Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 57, in loadAddons
    __import__(dir)
  File "/home/br/.local/share/Anki2/addons21/874215009/__init__.py", line 6, in <module>
    from . import advancedbrowser
  File "/home/br/.local/share/Anki2/addons21/874215009/advancedbrowser/__init__.py", line 1, in <module>
    from .core import AdvancedBrowser
  File "/home/br/.local/share/Anki2/addons21/874215009/advancedbrowser/core.py", line 14, in <module>
    from . import config
  File "/home/br/.local/share/Anki2/addons21/874215009/advancedbrowser/config.py", line 36, in <module>
    mw.addonManager.setConfigUpdatedAction(__name__,update)
AttributeError: 'AddonManager' object has no attribute 'setConfigUpdatedAction'

**Comment by honis56** [comment]
Debuginformationen:
Anki 2.1.0beta36 Python 3.6.9 Qt 5.9.5 PyQt 5.10.1
Platform: Linux
Flags: frz=False ao=True 

Caught exception:
File "/usr/share/anki/aqt/main.py", line 171, in onOpenProfile
self.loadProfile(self.profileDiag.closeWithoutQuitting)
File "/usr/share/anki/aqt/main.py", line 244, in loadProfile
if not self.loadCollection():
File "<decorator-gen-2>", line 2, in loadCollection
File "/usr/share/anki/anki/hooks.py", line 66, in decorator_wrapper
return repl(*args, **kwargs)
File "/usr/share/anki/anki/hooks.py", line 58, in repl
return new(*args, **kwargs)
File "/home/br/.local/share/Anki2/addons21/874215009/advancedbrowser/basic_fields.py", line 75, in myLoadCollection
mw.col.db._db.create_function("nameForDeck", 1, self.nameForDeck)
<class 'AttributeError'>: 'NoneType' object has no attribute 'db'
