### ISSUE TITLE
Not compatible With Anki 2.1.21

### ISSUE THREAD

**Issue by silentcicada1** [hssm/advanced-browser#64]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.21 (8960d12a) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.1
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-03-07 21:38:10
Add-ons possibly involved: ⁨Showing time in browser, Advanced Browser⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

Caught exception:
Traceback (most recent call last):
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 94, in data
    return super(AdvancedDataModel, self).data(index, role)
  File "aqt/browser.py", line 145, in data
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 98, in columnData
    returned = self._columnData(self, index)
  File "/Users/rachelstandifird/Library/Application Support/Anki2/addons21/1243668133/init.py", line 53, in columnData
    return fmtTimeSpan(c.ivl*86400)
NameError: name 'fmtTimeSpan' is not defined

**Comment by silentcicada1** [comment]
Issue seems to have resolved itself with 2.1.21 beta4 thanks
