### ISSUE TITLE
Not compatible with Anki 2.1.22

### ISSUE THREAD

**Issue by AnKingMed** [hssm/advanced-browser#65]
Error message when opening the browser:

Anki 2.1.22 (131d37dc) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.3
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-03-09 19:11:22
Add-ons possibly involved: ⁨Advanced Browser⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 31, in cmd
  File "aqt/webview.py", line 97, in _onCmd
  File "aqt/webview.py", line 500, in _onBridgeCmd
  File "aqt/toolbar.py", line 154, in _linkHandler
  File "aqt/toolbar.py", line 172, in _browseLinkHandler
  File "aqt/main.py", line 991, in onBrowse
  File "aqt/__init__.py", line 93, in open
  File "/Users/Nick/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 288, in __init__
    runHook("advBrowserLoaded", self)
  File "anki/hooks.py", line 611, in runHook
  File "/Users/Nick/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/custom_fields.py", line 30, in onAdvBrowserLoad
    cs = CardStats(None, None)
  File "anki/stats.py", line 28, in __init__
AttributeError: 'NoneType' object has no attribute 'weakref'

**Comment by AnKingMed** [comment]
Update on this.. Damien addressed this: https://anki.tenderapp.com/discussions/beta-testing/1842-syncing-message
