### ISSUE TITLE
crashed on macbook air

### ISSUE THREAD

**Issue by sibilek** [hssm/advanced-browser#85]
Thank you for this great add-on. it is crashed when I am using it. this is the debug code. have a great day

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.23 (de9543ff) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.3
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-04-20 23:38:24
Add-ons possibly involved: ⁨1237621971, Advanced Browser⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 31, in cmd
  File "aqt/webview.py", line 97, in _onCmd
  File "aqt/webview.py", line 500, in _onBridgeCmd
  File "aqt/toolbar.py", line 154, in _linkHandler
  File "aqt/toolbar.py", line 172, in _browseLinkHandler
  File "aqt/main.py", line 991, in onBrowse
  File "aqt/__init__.py", line 93, in open
  File "/Users/sinanbilek/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 292, in __init__
    origInit(self, mw)
  File "aqt/browser.py", line 595, in __init__
  File "aqt/browser.py", line 851, in setupEditor
  File "aqt/editor.py", line 83, in __init__
  File "aqt/editor.py", line 148, in setupWeb
  File "anki/hooks.py", line 622, in runFilter
  File "/Users/sinanbilek/Library/Application Support/Anki2/addons21/1237621971/addTable.py", line 380, in setupEditorButtonsFilter
  File "/Users/sinanbilek/Library/Application Support/Anki2/addons21/1237621971/addTable.py", line 32, in gc
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by hssm** [comment]
This error is coming from the `Add Table` add-on.

**Comment by ijgnd** [comment]
@sibilek : Your error looks like you have an error in your config. You could reset the config in the `Configure 'Add Table'` window with the button `Restore Defaults` in the lower left corner. If the error still occurs we could continue at https://github.com/ijgnd/anki__editor_add_table/issues

**Comment by sibilek** [comment]
Thanks
