### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type AdvancedBrowser has been deleted

### ISSUE THREAD

**Issue by galantra** [hssm/advanced-browser#88]
I left Anki open for a long time without doing anything (review window + edit card window were open). Then I got this error whenever I wanted to close Anki, switch profile, make a backup, or sync:

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-03 10:42:49

Caught exception:
Traceback (most recent call last):
  File "C:\Users\user\PortableApps\AnkiPortable\Anki2\addons21\883617253\__init__.py", line 12, in reloadCollection
    mw.unloadCollection(mw.loadCollection)
  File "aqt\main.py", line 476, in unloadCollection
  File "aqt\main.py", line 747, in closeAllWindows
  File "C:\Users\user\PortableApps\AnkiPortable\Anki2\addons21\354407385\__init__.py", line 124, in closeAll
    return super().closeAll(onsuccess)
  File "aqt\__init__.py", line 121, in closeAll
RuntimeError: wrapped C/C++ object of type AdvancedBrowser has been deleted

```

**Comment by hssm** [comment]
I'm going to close this since I don't think the add-on is related to this issue. It seems to be a resource management bug in the underlying toolkit or even Anki, and this add-on is implicated simply because it takes over the original Browser object.
