### ISSUE TITLE
Anki 2.1.25 error (windows 10)

### ISSUE THREAD

**Issue by beepboopbeep3000** [hssm/advanced-browser#89]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.25 (898801eb) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-06 09:35:27

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 34, in cmd
  File "aqt\webview.py", line 114, in _onCmd
  File "aqt\webview.py", line 518, in _onBridgeCmd
  File "aqt\toolbar.py", line 154, in _linkHandler
  File "aqt\toolbar.py", line 178, in _syncLinkHandler
  File "aqt\main.py", line 868, in onSync
  File "aqt\main.py", line 519, in unloadCollection
  File "aqt\main.py", line 783, in closeAllWindows
  File "aqt\__init__.py", line 107, in closeAll
  File "aqt\main.py", line 517, in callback
  File "aqt\main.py", line 872, in _onSync
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-124>", line 2, in loadCollection
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 629, in repl
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-122>", line 2, in loadCollection
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 629, in repl
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-120>", line 2, in loadCollection
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 630, in repl
  File "C:\Users\david\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\basic_fields.py", line 75, in myLoadCollection
    mw.col.db._db.create_function("nameForDeck", 1, self.nameForDeck)
AttributeError: 'DBProxy' object has no attribute '_db'

**Comment by hssm** [comment]
How did you install this add-on? The version you have is not compatible with the newest Anki version, but the info above says it's attempted an update recently. Did it not auto-update?

Newest version should work.

**Comment by beepboopbeep3000** [comment]
I installed this as part of an add-on package from Ankingmed.com a while back.

Anki appears to have updated the add-on yesterday and now I'm no longer getting the error.  I'm not sure why it didn't update the add-on earlier.

Thanks!
