### ISSUE TITLE
2.1.26 release candidate error

### ISSUE THREAD

**Issue by AnKingMed** [hssm/advanced-browser#90]
Got this error message when trying to get to the browser:

Anki 2.1.26 (2a0d40e1) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.4
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-05-07 14:57:29
Add-ons possibly involved: ⁨Advanced Browser, The KING of Study Timers⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 34, in cmd
  File "aqt/webview.py", line 114, in _onCmd
  File "aqt/webview.py", line 518, in _onBridgeCmd
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-122>", line 2, in _linkHandler
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 635, in repl
  File "/Users/Nick/Library/Application Support/Anki2/addons21/The KING of Study Timers/__init__.py", line 571, in myLinkHandler
    return _old(self, url)
  File "aqt/toolbar.py", line 154, in _linkHandler
  File "aqt/toolbar.py", line 172, in _browseLinkHandler
  File "aqt/main.py", line 1022, in onBrowse
  File "aqt/__init__.py", line 95, in open
  File "/Users/Nick/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 207, in __init__
    origInit(self, mw)
TypeError: newBrowserInit() takes 2 positional arguments but 3 were given

**Comment by hssm** [comment]
It seems that the issue is caused by the `The KING of Study Timers` add-on you have. Does it try to launch a new browser instance in that link handler? Perhaps it is not passing in the right arguments.

I suspect this will continue to happen even without Advanced Browser installed since it has the same init definition as the stock browser.

**Comment by AnKingMed** [comment]
Looks like it was actually Better tags and not either of these. Sorry I should have tested that more!
