### ISSUE TITLE
Crash with anki 2.1.26

### ISSUE THREAD

**Issue by josem8f** [hssm/advanced-browser#91]
Just updated to 2.1.26 . Clicking in browse exception throws.

Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-09 18:10:25

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 34, in cmd
  File "aqt\webview.py", line 114, in _onCmd
  File "aqt\webview.py", line 518, in _onBridgeCmd
  File "aqt\toolbar.py", line 154, in _linkHandler
  File "aqt\toolbar.py", line 172, in _browseLinkHandler
  File "aqt\main.py", line 1022, in onBrowse
  File "aqt\__init__.py", line 95, in open
  File "C:\Users\jomac\AppData\Roaming\Anki2\addons21\874215009\advancedbrowser\core.py", line 207, in __init__
    origInit(self, mw)
  File "aqt\browser.py", line 588, in __init__
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-16>", line 2, in setupUi
  File "lib\site-packages\anki\hooks.py", line 638, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 630, in repl
  File "C:\Users\jomac\AppData\Roaming\Anki2\addons21\1924690148\__init__.py", line 57, in mySetupUi
    mw.col.db._db.create_function("stripCombining", 1, stripCombining)
AttributeError: 'DBProxy' object has no attribute '_db'

**Comment by josem8f** [comment]
Seems it's happening with some more addons. I'm closing until discover what happens.

**Comment by hssm** [comment]
It's from my [other add-on](https://ankiweb.net/shared/info/1924690148) which isn't supported or required as of Anki 2.1.24. I assumed Anki would disable it automatically since it's marked as unsupported on that version, but maybe it doesn't and tries to run it anyway.

**Comment by hssm** [comment]
Actually I made a mistake with the version limits on AnkiWeb so it kept trying to use the add-on on 23+ instead of <= 23. I fixed that now. Maybe it'll automatically disable it now on the next add-on update check.

**Comment by josem8f** [comment]
You're correct. I was updating from 2.1.15 and had both of them. I've had to remove both plugins and reinstall this one. 

Even though, there may be some bug in Anki, it doesn't close properly. I can only open Anki once, the next times it shows the another instance is running wnidow.
I'ts functional so for me no probs, I'll wait for next anki update.

Thanks for helping!
