### ISSUE TITLE
Not compatible with latest Anki release

### ISSUE THREAD

**Issue by bradydjohnson** [hssm/advanced-browser#92]
Got the following error. 

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.4
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-05-22 12:40:00
Add-ons possibly involved: ⁨Advanced Browser, The KING of Study Timers⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 34, in cmd
  File "aqt/webview.py", line 114, in _onCmd
  File "aqt/webview.py", line 518, in _onBridgeCmd
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-66>", line 2, in _linkHandler
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 635, in repl
  File "/Users/bradyjohnson/Library/Application Support/Anki2/addons21/907028815/__init__.py", line 585, in myLinkHandler
    return _old(self, url)
  File "aqt/toolbar.py", line 154, in _linkHandler
  File "aqt/toolbar.py", line 178, in _syncLinkHandler
  File "aqt/main.py", line 868, in onSync
  File "aqt/main.py", line 519, in unloadCollection
  File "aqt/main.py", line 783, in closeAllWindows
  File "aqt/__init__.py", line 108, in closeAll
  File "aqt/main.py", line 517, in callback
  File "aqt/main.py", line 872, in _onSync
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-104>", line 2, in loadCollection
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 629, in repl
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-102>", line 2, in loadCollection
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 629, in repl
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-100>", line 2, in loadCollection
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 630, in repl
  File "/Users/bradyjohnson/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/basic_fields.py", line 75, in myLoadCollection
    mw.col.db._db.create_function("nameForDeck", 1, self.nameForDeck)
AttributeError: 'DBProxy' object has no attribute '_db'

```

**Comment by hssm** [comment]
It's supported but your version of the add-on is old, and it hasn't updated automatically for some reason (same as https://github.com/hssm/advanced-browser/issues/89). Try removing it and re-installing it.
