### ISSUE TITLE
error IntegralValueOutOfRange - Anki 2.1.26

### ISSUE THREAD

**Issue by omega3** [hssm/advanced-browser#97]
```
Add-ons possibly involved: ⁨Advanced Browser⁩

Caught exception:
Traceback (most recent call last):
  File "/home/user/.local/share/Anki2/addons21/874215009/advancedbrowser/core.py", line 172, in paint
    fld = self.browser.model.getFld(index)
  File "/home/user/.local/share/Anki2/addons21/874215009/advancedbrowser/core.py", line 72, in getFld
    model = self.getCard(index).note().model()
  File "aqt/browser.py", line 93, in getCard
  File "anki/collection.py", line 287, in getCard
  File "anki/cards.py", line 44, in __init__
  File "anki/cards.py", line 50, in load
  File "anki/rsbackend.py", line 500, in get_card
  File "anki/rsbackend.py", line 257, in _run_command
anki.rsbackend.DBError: DBError { info: "IntegralValueOutOfRange(8, -633)", kind: Other }
```
Version 2.1.26 (70784154)
Python 3.8.1 Qt 5.14.1 PyQt 5.14.1

Operating System: Manjaro Linux
KDE Plasma Version: 5.19.3
KDE Frameworks Version: 5.72.0
Qt Version: 5.15.0
Kernel Version: 5.7.9-1-MANJARO
OS Type: 64-bit

**Comment by omega3** [comment]
The same for new version:

```
Debug info:
Anki 2.1.29 (bbff62bf) Python 3.8.1 Qt 5.15.0 PyQt 5.15.0
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-07-29 19:50:32
Add-ons possibly involved: ⁨Advanced Browser⁩

Caught exception:
Traceback (most recent call last):
  File "/home/user/.local/share/Anki2/addons21/874215009/advancedbrowser/core.py", line 172, in paint
    fld = self.browser.model.getFld(index)
  File "/home/user/.local/share/Anki2/addons21/874215009/advancedbrowser/core.py", line 72, in getFld
    model = self.getCard(index).note().model()
  File "aqt/browser.py", line 96, in getCard
  File "anki/collection.py", line 306, in getCard
  File "anki/cards.py", line 45, in __init__
  File "anki/cards.py", line 51, in load
  File "anki/rsbackend_gen.py", line 311, in get_card
  File "anki/rsbackend.py", line 265, in _run_command
anki.rsbackend.DBError: DBError { info: "IntegralValueOutOfRange(9, -663)", kind: Other }
```

**Comment by hssm** [comment]
I'll need a copy of your collection to understand this issue.

**Comment by omega3** [comment]
sample of collection
[Anki.zip](https://github.com/hssm/advanced-browser/files/5010226/Anki.zip)

and new report

```
Anki 2.1.29 (bbff62bf) Python 3.8.1 Qt 5.15.0 PyQt 5.15.0
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-01 11:49:03
Add-ons possibly involved: ⁨Advanced Browser⁩

Caught exception:
Traceback (most recent call last):
  File "/home/user/.local/share/Anki2/addons21/874215009/advancedbrowser/core.py", line 172, in paint
    fld = self.browser.model.getFld(index)
  File "/home/user/.local/share/Anki2/addons21/874215009/advancedbrowser/core.py", line 72, in getFld
    model = self.getCard(index).note().model()
  File "aqt/browser.py", line 96, in getCard
  File "anki/collection.py", line 306, in getCard
  File "anki/cards.py", line 45, in __init__
  File "anki/cards.py", line 51, in load
  File "anki/rsbackend_gen.py", line 311, in get_card
  File "anki/rsbackend.py", line 265, in _run_command
anki.rsbackend.DBError: DBError { info: "IntegralValueOutOfRange(9, -723)", kind: Other }

Caught exception:
Traceback (most recent call last):
  File "/home/kompik/.local/share/Anki2/addons21/874215009/advancedbrowser/core.py", line 172, in paint
    fld = self.browser.model.getFld(index)
  File "/home/kompik/.local/share/Anki2/addons21/874215009/advancedbrowser/core.py", line 72, in getFld
    model = self.getCard(index).note().model()
  File "aqt/browser.py", line 96, in getCard
  File "anki/collection.py", line 306, in getCard
  File "anki/cards.py", line 45, in __init__
  File "anki/cards.py", line 51, in load
  File "anki/rsbackend_gen.py", line 311, in get_card
  File "anki/rsbackend.py", line 265, in _run_command
anki.rsbackend.DBError: DBError { info: "IntegralValueOutOfRange(9, -723)", kind: Other }

Caught exception:
Traceback (most recent call last):
  File "/home/kompik/.local/share/Anki2/addons21/874215009/advancedbrowser/core.py", line 172, in paint
    fld = self.browser.model.getFld(index)
  File "/home/kompik/.local/share/Anki2/addons21/874215009/advancedbrowser/core.py", line 72, in getFld
    model = self.getCard(index).note().model()
  File "aqt/browser.py", line 96, in getCard
  File "anki/collection.py", line 306, in getCard
  File "anki/cards.py", line 45, in __init__
  File "anki/cards.py", line 51, in load
  File "anki/rsbackend_gen.py", line 311, in get_card
  File "anki/rsbackend.py", line 265, in _run_command
anki.rsbackend.DBError: DBError { info: "IntegralValueOutOfRange(9, -723)", kind: Other }

Caught exception:
Traceback (most recent call last):
  File "/home/kompik/.local/share/Anki2/addons21/874215009/advancedbrowser/core.py", line 172, in paint
    fld = self.browser.model.getFld(index)
  File "/home/kompik/.local/share/Anki2/addons21/874215009/advancedbrowser/core.py", line 72, in getFld
    model = self.getCard(index).note().model()
  File "aqt/browser.py", line 96, in getCard
  File "anki/collection.py", line 306, in getCard
  File "anki/cards.py", line 45, in __init__
  File "anki/cards.py", line 51, in load
  File "anki/rsbackend_gen.py", line 311, in get_card
  File "anki/rsbackend.py", line 265, in _run_command
anki.rsbackend.DBError: DBError { info: "IntegralValueOutOfRange(9, -723)", kind: Other }

Caught exception:
Traceback (most recent call last):
  File "/home/kompik/.local/share/Anki2/addons21/874215009/advancedbrowser/core.py", line 172, in paint
    fld = self.browser.model.getFld(index)
  File "/home/kompik/.local/share/Anki2/addons21/874215009/advancedbrowser/core.py", line 72, in getFld
    model = self.getCard(index).note().model()
  File "aqt/browser.py", line 96, in getCard
  File "anki/collection.py", line 306, in getCard
  File "anki/cards.py", line 45, in __init__
  File "anki/cards.py", line 51, in load
  File "anki/rsbackend_gen.py", line 311, in get_card
  File "anki/rsbackend.py", line 265, in _run_command
anki.rsbackend.DBError: DBError { info: "IntegralValueOutOfRange(9, -723)", kind: Other }

```

**Comment by hssm** [comment]
The issue turns out to be with your collection: you have two cards with negative intervals and the Anki internals refuse to load the cards as they are invalid. If you try to review those cards they will fail in the same way; the add-on happened to access the card details before a problem appeared elsewhere.

If you know how you ended up with these negative values you should try to fix the problem at the source.

To fix the problem with your deck now, load the browser without any add-ons and find the cards - they will appear blank in the browser. Click on them, ignore the error, then use the menu option to reschedule the cards to an interval you prefer.

**Comment by omega3** [comment]
When I sorted cards in this sample deck I have intervals ranging from 3 days to 1,8 years. I am not sure how you spotted cards with negative interval. Like this?

`prop:due=-1`
    cards due yesterday that haven’t been answered yet

Anki doesn't list anything with this command. And until this version I didn't have problems like this.

**Comment by hssm** [comment]
I just scrolled through the browser:
![image](https://user-images.githubusercontent.com/789082/89118364-907f8980-d4e8-11ea-9e2a-17fb3639112d.png)

Sorting by interval puts them at the top.

**Comment by omega3** [comment]
You are correct. Thank you very much for support.
